### PR TITLE
add simpleBusyRecord

### PR DESCRIPTION
**Pull request by mrkraimer**
simpleBusyRecord is a drastically simplified version of the synapps  busyRecord.
It was added so that ca provider (In particular channelPut)  from both pvAccessCPP and pvAccessJava could be tested, without requiring anything from synapps.

Formally the ca providers  only supported put with callback.
The new versions now  support put both with and without callback.
The default, just like caput and qsrv, is put without callback.
To ask for put with callback the client must specify
record[block=true]
in pvRequest when creating the channelPut.

### CODE REVIEW

**Comment by anjohnson** [comment]
Hi Marty, take a look at the commits I made to the exampleCPP master branch this week which cleaned up the Windows DLL builds on the APS Jenkins. Sorry I should have emailed you about them...

- Andrew

**Comment by mrkraimer** [comment]
Note that the failure is only in build #38 and the error is

/usr/bin/i686-w64-mingw32-g++ -o example.dll -shared -Wl,--out-implib,libexample.dll.a -L/home/travis/build/epics-base/exampleCPP/database/lib/win32-x86-mingw        -m32    -static-libgcc -static-libstdc++            simpleBusyRecord.obj          -lws2_32 -ladvapi32 -luser32 -lkernel32 -lwinmm 
simpleBusyRecord.obj:simpleBusyRecord.c:(.text+0x39): undefined reference to `_imp__epicsAssert'
simpleBusyRecord.obj:simpleBusyRecord.c:(.text+0x56d): undefined reference to `_imp__recGblGetTimeStamp'
simpleBusyRecord.obj:simpleBusyRecord.c:(.text+0x588): undefined reference to `_imp__db_post_events'
simpleBusyRecord.obj:simpleBusyRecord.c:(.text+0x5a9): undefined reference to `_imp__recGblFwdLink'
simpleBusyRecord.obj:simpleBusyRecord.c:(.text+0x5dd): undefined reference to `_imp__recGblResetAlarms'

Andrew can You look at
/home/epicsv4/masterCPP/exampleCPP/database/ioc/src/Makefile.
It may be the source of the error.
In particular look for SYS_LIBS_WIN32 += ws2_32
Do You see the problem?

Note that the Makefille has the following
mrk> cat Makefile 
TOP=../..
include $(TOP)/configure/CONFIG
...
LIBRARY_IOC += example

DBD += exampleDatabase.dbd
DBDINC += simpleBusyRecord
example_SRCS += simpleBusyRecord.c

PROD_IOC += exampleDatabase
# <name>_registerRecordDeviceDriver.cpp will be created from <name>.dbd
exampleDatabase_SRCS += exampleDatabase_registerRecordDeviceDriver.cpp
exampleDatabase_SRCS_DEFAULT += exampleDatabaseMain.cpp
exampleDatabase_SRCS_vxWorks += -nil-

# The following adds support from base/src/vxWorks
exampleDatabase_OBJS_vxWorks += $(EPICS_BASE_BIN)/vxComLibrary

exampleDatabase_LIBS += exampleDatabase
exampleDatabase_LIBS += pvDatabase qsrv pvAccessIOC pvAccess pvAccessCA nt pvData
exampleDatabase_LIBS += example
exampleDatabase_LIBS += $(EPICS_BASE_IOC_LIBS)
exampleDatabase_SYS_LIBS_WIN32 += ws2_32


#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

**Comment by anjohnson** [comment]
I don't think the Microsoft ws2_32 library has anything to do with the linker errors. I'm pretty sure they are happening because you're missing this line from the Makefile:
```
example_LIBS += $(EPICS_BASE_IOC_LIBS)
```
You're creating a new library `example` and on Windows it needs to be linked against its all dependent libraries.

**Comment by mrkraimer** [comment]
Thanks Andrew!!

**Pull request merged**
