### PR TITLE
static base now builds; INC now follows pvaClientCPP

### PR DESCRIPTION
**Pull request by mrkraimer**
This now builds with a static build of epics base.
The way INC is implemented now follows more closely pvaClientCPP.

### CODE REVIEW

**Comment by anjohnson** [comment]
Not tested, but looks reasonable to me.

**Comment by mrkraimer** [comment]
Before merge there are two things to do:

1) Most example have a directory src/code.
This directory is not needed since the *.cpp files can be moved to src.
Then the examples more closely follow how Michael suggested to implement src/pv

2) The following still fails with statically build base BUT not if base is  build shared

mrk> pwd
/home/epicsv4/master/exampleCPP/test
mrk> make runtests
make -C O.linux-x86_64 -f ../Makefile TOP=../.. \
    T_A=linux-x86_64 runtests
make[1]: Entering directory '/home/epicsv4/master/exampleCPP/test/O.linux-x86_64'
perl -MTest::Harness -e 'runtests @ARGV if @ARGV;' pvaClientTest.t pvaClientTestPutData.t pvaClientTestGetData.t pvaClientTestMonitorData.t pvaClientTestPutGetMonitor.t pvaClientTestPutGet.t
..................................................................
pvaClientTest.t ............... ok   
pvaClientTestPutData.t ........ Dubious, test returned 139 (wstat 35584, 0x8b00)
No subtests run 
pvaClientTestGetData.t ........ Dubious, test returned 139 (wstat 35584, 0x8b00)
No subtests run 
pvaClientTestMonitorData.t .... Dubious, test returned 139 (wstat 35584, 0x8b00)
No subtests run 
pvaClientTestPutGetMonitor.t .. ok     
pvaClientTestPutGet.t ......... ok   

Test Summary Report
-------------------
pvaClientTestPutData.t      (Wstat: 35584 Tests: 0 Failed: 0)
  Non-zero exit status: 139
  Parse errors: No plan found in TAP output
pvaClientTestGetData.t      (Wstat: 35584 Tests: 0 Failed: 0)
  Non-zero exit status: 139
  Parse errors: No plan found in TAP output
pvaClientTestMonitorData.t  (Wstat: 35584 Tests: 0 Failed: 0)
  Non-zero exit status: 139
  Parse errors: No plan found in TAP output
Files=6, Tests=29, 17 wallclock secs ( 0.03 usr  0.01 sys +  0.21 cusr  0.09 csys =  0.34 CPU)
Result: FAIL
Failed 3/6 test programs. 0/29 subtests failed.
/home/install/epics/base-3.14.12.5STATICBUILD/configure/RULES_BUILD:341: recipe for target 'runtests' failed
make[1]: [runtests] Error 255 (ignored)
make[1]: Leaving directory '/home/epicsv4/master/exampleCPP/test/O.linux-x86_64'
mrk> 


BUT I do not understand "Parse errors: No plan found in TAP output"
Andrew,

Can you give me a clue?

**Comment by mdavidsaver** [comment]
Probably an immediate crash.  Run one of the failing tests manually.

**Comment by mrkraimer** [comment]
On 02/08/2016 07:26 AM, mdavidsaver wrote:
> Probably an immediate crash. Run one of the failing tests manually.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/5#issuecomment-181344257>.
>

OK I looked at tests that failed.
The three were pvaClientTestGetData.cpp, pvaClientTestMonitorData.cpp, 
and pvaClientTestPutData.cpp

All three segfaulted.

I made similar changes to all three and now "make runtests" now works.

BUT I do not like the changes I made.

For example

diff --git a/test/pvaClientTestGetData.cpp b/test/pvaClientTestGetData.cpp
index 74a0af3..c6e649c 100644
--- a/test/pvaClientTestGetData.cpp
+++ b/test/pvaClientTestGetData.cpp
@@ -22,10 +22,10 @@ using namespace epics::pvData;
  using namespace epics::pvAccess;
  using namespace epics::pvaClient;

-static PvaClientPtr pvaClient = PvaClient::create();
-static FieldCreatePtr fieldCreate = getFieldCreate();
-static StandardFieldPtr standardField = getStandardField();
-static PVDataCreatePtr pvDataCreate = getPVDataCreate();
+static PvaClientPtr pvaClient;
+static FieldCreatePtr fieldCreate;
+static StandardFieldPtr standardField;
+static PVDataCreatePtr pvDataCreate;

  static void testDouble()
  {
@@ -188,13 +188,21 @@ static void testDoubleArray()

  MAIN(pvaClientTestGetData)
  {
+    pvaClient = PvaClient::create();
+    fieldCreate = getFieldCreate();
+    standardField = getStandardField();
+    pvDataCreate = getPVDataCreate();
+
      testPlan(26);
      testDiag("=== pvaClientTestGetData ===");

      testDouble();
      testDoubleArray();
-
      testDone();
+pvaClient.reset();
+fieldCreate.reset();
+standardField.reset();
+pvDataCreate.reset();
      return 0;
  }

Why did I have to make these changes for static build?

**Comment by anjohnson** [comment]
I can't explain why your original code doesn't work for you when linked statically. I just checked out your version before that last commit and everything passes for me:
```
tux% make runtests
make -f ../Makefile TOP=../.. T_A=linux-x86_64-static  runtests
make[1]: Entering directory '/local/anj/v4/exampleCPP/test/O.linux-x86_64-static'
perl -MTest::Harness -e 'runtests @ARGV if @ARGV;' pvaClientTest.t pvaClientTestPutData.t pvaClientTestGetData.t pvaClientTestMonitorData.t pvaClientTestPutGetMonitor.t pvaClientTestPutGet.t
pvaClientTest.t ............... ok   
pvaClientTestPutData.t ........ ok     
pvaClientTestGetData.t ........ ok     
pvaClientTestMonitorData.t .... ok     
pvaClientTestPutGetMonitor.t .. ok     
pvaClientTestPutGet.t ......... ok   
All tests successful.
Files=6, Tests=119, 17 wallclock secs ( 0.07 usr  0.02 sys +  0.38 cusr  0.21 csys =  0.68 CPU)
Result: PASS
make[1]: Leaving directory '/local/anj/v4/exampleCPP/test/O.linux-x86_64-static'
```
How are you doing your static build? I added a new `linux-x86_64-static` cross-compiled target to my existing Base with just 2 new files in `base/configure/os`:
``` Makefile
# CONFIG.Common.linux-x86_64-static
# Include definitions from the non-static target
include $(CONFIG)/os/CONFIG.Common.linux-x86_64

# Overrides
STATIC_BUILD = YES
SHARED_LIBRARIES = NO
```
``` Makefile
# CONFIG_SITE.Common.linux-x86_64-static
# Include definitions from the non-static target
include $(CONFIG)/os/CONFIG_SITE.Common.linux-x86_64
```
Doing it this way is much easier than having a separate build of Base or editing those settings in the `configure/os/CONFIG_SITE` file and rebuilding everything.

Your `test` directory is missing a couple of source files the Makefile names for RTEMS `rtemsTestHarness.c` and `rtemsConfig.c` so it doesn't build for me at the moment, but the files don't exist in the original pvaClientTestCPP module either. There are copies in pvDataCPP which obviously came from Michael. You might want to just disable RTEMS builds for now by commenting out the line `PROD_RTEMS += rtemsTestHarness`.

**Comment by mrkraimer** [comment]
On 02/08/2016 03:06 PM, Andrew Johnson wrote:
>
> I can't explain why your original code doesn't work for you when 
> linked statically. I just checked out your version before that last 
> commit and everything passes for me:
>
> |tux% make runtests make -f ../Makefile TOP=../.. 
> T_A=linux-x86_64-static runtests make[1]: Entering directory 
> '/local/anj/v4/exampleCPP/test/O.linux-x86_64-static' perl 
> -MTest::Harness -e 'runtests @ARGV if @ARGV;' pvaClientTest.t 
> pvaClientTestPutData.t pvaClientTestGetData.t 
> pvaClientTestMonitorData.t pvaClientTestPutGetMonitor.t 
> pvaClientTestPutGet.t pvaClientTest.t ............... ok 
> pvaClientTestPutData.t ........ ok pvaClientTestGetData.t ........ ok 
> pvaClientTestMonitorData.t .... ok pvaClientTestPutGetMonitor.t .. ok 
> pvaClientTestPutGet.t ......... ok All tests successful. Files=6, 
> Tests=119, 17 wallclock secs ( 0.07 usr 0.02 sys + 0.38 cusr 0.21 csys 
> = 0.68 CPU) Result: PASS make[1]: Leaving directory 
> '/local/anj/v4/exampleCPP/test/O.linux-x86_64-static'|

|Strange that it worked for You.
Also I would really like to know why the changes I made fixed the 
problem for me.
I explained what I did in my previous message.
|
> ||
>
> How are you doing your static build?
>

I followed the instructions You gave in a previous message You send to me.

mrk> pwd
/home/install/epics/base-3.14.12.5/configure
mrk> diff CONFIG_SITE 
/home/install/epics/base-3.14.12.5STATICBUILD/configure
134c134
< SHARED_LIBRARIES=YES
---
 > SHARED_LIBRARIES=NO
139c139
< STATIC_BUILD=NO
---
 > STATIC_BUILD=YES
mrk>

> I added a new |linux-x86_64-static| cross-compiled target to my 
> existing Base with just 2 new files in |base/configure/os|:
>
> # CONFIG.Common.linux-x86_64-static
> # Include definitions from the non-static target
> include  $(CONFIG)/os/CONFIG.Common.linux-x86_64
>
> # Overrides
> STATIC_BUILD  = YES
> SHARED_LIBRARIES  = NO
> # CONFIG_SITE.Common.linux-x86_64-static
> # Include definitions from the non-static target
> include  $(CONFIG)/os/CONFIG_SITE.Common.linux-x86_64
>
> Doing it this way is much easier than having a separate build of Base 
> or editing those settings in the |configure/os/CONFIG_SITE| file and 
> rebuilding everything.
>

I have as set of bash scripts that make it easy for me to change.
One script determines the set of projects to build.
I only have to run this if I want to change the set.

Then I just edit RELEASE.local and then just

buildCPP.

This in turn runs:

makePullCPP
makeCleanCPP
makeBuildCPP

I can also run each of these scripts separately.

Each command send sysout and syserr to seprate files.
Thus I see files:
stderrBuildCPP  stderrPullCPP   stdoutCleanCPP
stderrCleanCPP  stdoutBuildCPP  stdoutPullCPP

> Your |test| directory is missing a couple of source files the Makefile 
> names for RTEMS |rtemsTestHarness.c| and |rtemsConfig.c| so it doesn't 
> build for me at the moment, but the files don't exist in the original 
> pvaClientTestCPP module either. There are copies in pvDataCPP which 
> obviously came from Michael. You might want to just disable RTEMS 
> builds for now by commenting out the line |PROD_RTEMS += 
> rtemsTestHarness|.
>

OK I commented out the line you suggest and pushed.

I will merge this pull request when I see that all checks succeed.

I will start trying to create |rtemsTestHarness.c| and |rtemsConfig.c|
I will merge this pull request and create a new pull request when I am 
ready.
I am not prepared to build RTEMS and may need some help.

**Pull request merged**
