### PR TITLE
Add examples from pvDatabaseCPP and pvaClientCPP

### PR DESCRIPTION
**Pull request by mrkraimer**
I have added the examples from pvDatabaseCPP and pvaClientCPP.
After the merge the examples will be removed from pvDatabaseCPP and pvaClientCPP.

### CODE REVIEW

**Comment by mrkraimer** [comment]
Unless someone objects I will merge tomorrow Jan 13 2016.
Marty

**Comment by anjohnson** [comment]
Marty: in case you haven't seen this on the pull request page at github, your last commit caused the build-time checks to fail for the module. The console output from one of the builds is at https://openepics.ci.cloudbees.com/view/EPICS%20V4%20C++/job/exampleCPP_PullRequests/lastFailedBuild/BASE=3.14.12.5,USE_MB=MB_NO/console which may indicate that the problem is with the jenkins/cloudbees_build script, but you should probably fix it and ensure the checks succeed before merging this code.

**Comment by dhickin** [comment]
<p>I think you just need the change</p>
<pre>-make -C HelloWorld distclean all
+make distclean all
</pre>
<p>in jenkins/cloudbees_build.</p>
<p>Perhap also reorder the makes - distclean the Channel Archiver service first.</p>

**Comment by dhickin** [comment]
<p>Can we put a <b>Hold</b> on merging this until we resolve the issues 1,2 and 4 below? Ideally this should be discussed in a telecon before a merge.</p>

1) I notice the source in many examples is now split with the headers in pv and the cpps and dbds in code. Is this to address Michael's concern over IDEs? If so shouldn't we make the decision over  whether we're going to make this move for all modules before we merge this? If not then I'm not sure why it's organised this way.

Also as I've commented previously through the list:

2) test

Is this really test code or is it an example? If it's genuinely test code it would be better, if possible, to keep it in the [pvaClient] module. If not possible  then that's OK, but it shouldn't just be called test. test implies a test for the whole exampleCPP module. It needs a more descriptive name, e.g. pvaClientTest or pvaClientExamples. 

3) exampleXXX

Just a suggestion, but consider renaming these. These names made sense when they were part of pvDatabaseCPP. The word "example" told you they were examples and the user knew they were pvDatabase examples because they were in  pvDatabase. Now the user knows that these are examples because they are in exampleCPP, but won't know they are <em>pvDatabase</em> examples. So a name such as linkDatabase, linkDb, pvDatabaseLink, pvDbLink would be more useful. You can probably think of something better, but you get the idea. This one is more personal opinion, so it certainly doesn't gate making the merge.

4) In the interest of symmetry we should move the examples from pvaClentJava and pvDatabaseJava to exampleJava. Ideally we would have both pull requests ready together, but that's not necessary to do the C++ merge. However I do think we should have agreement that we are going to make the equivalent Java move and are going to do this imminently. Do we have this? Do you have time to complete the Java move? Is Greg OK with this for example? (Looking back through the mailing  list Greg did seem supportive.)

**Comment by mrkraimer** [comment]
On 01/12/2016 05:28 PM, Andrew Johnson wrote:
>
> Marty: in case you haven't seen this on the pull request page at 
> github, your last commit caused the build-time checks to fail for the 
> module. The console output from one of the builds is at 
> https://openepics.ci.cloudbees.com/view/EPICS%20V4%20C++/job/exampleCPP_PullRequests/lastFailedBuild/BASE=3.14.12.5,USE_MB=MB_NO/console 
> which may indicate that the problem is with the 
> jenkins/cloudbees_build script, but you should probably fix it and 
> ensure the checks succeed before merging this code.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/3#issuecomment-171080575>.
>

I have changed top level Makefile so that
make distclean

works properly.

But it still does not work properly.

It dies do a realClean in each subdirectory but only does a a
perl /home/install/epics/base-3.14.12.5/bin/linux-x86_64/cvsclean.pl

in the first subdirectory.

Andrew can You help?

Will the pull request pick up this change, which was made after the pull 
request was made.

**Comment by mrkraimer** [comment]
On 01/13/2016 07:03 AM, dhickin wrote:
>
> Can we put a *Hold* on merging this until we resolve the issues 1,2 
> and 4 below? Ideally this should be discussed in a telecon before a merge.
>
> 1) I notice the source in many examples is now split with the headers 
> in pv and the cpps and dbds in code. Is this to address Michael's 
> concern over IDEs? If so shouldn't we make the decision over whether 
> we're going to make this move for all modules before we merge this? If 
> not then I'm not sure why it's organised this way.
>

That is the reason why I made this change.
I thought we did decide to do this for all github repositories.
If not done for all repositories than problem still exists for IDEs.

> Also as I've commented previously through the list:
>
> 2) test
>
> Is this really test code or is it an example? If it's genuinely test 
> code it would be better, if possible, to keep it in the [pvaClient] 
> module. If not possible then that's OK, but it shouldn't just be 
> called test. test implies a test for the whole exampleCPP module. It 
> needs a more descriptive name, e.g. pvaClientTest or pvaClientExamples.
>

The test requires a running database, which is why it can not be in 
pvaClientCPP.

> 3) exampleXXX
>
> Just a suggestion, but consider renaming these. These names made sense 
> when they were part of pvDatabaseCPP. The word "example" told you they 
> were examples and the user knew they were pvDatabase examples because 
> they were in pvDatabase. Now the user knows that these are examples 
> because they are in exampleCPP, but won't know they are /pvDatabase/ 
> examples. So a name such as linkDatabase, linkDb, pvDatabaseLink, 
> pvDbLink would be more useful. You can probably think of something 
> better, but you get the idea. This one is more personal opinion, so it 
> certainly doesn't gate making the merge.
>
> 4) In the interest of symmetry we should move the examples from 
> pvaClentJava and pvDatabaseJava to exampleJava. Ideally we would have 
> both pull requests ready together, but that's not necessary to do the 
> C++ merge. However I do think we should have agreement that we are 
> going to make the equivalent Java move and are going to do this 
> imminently. Do we have this? Do you have time to complete the Java 
> move? Is Greg OK with this for example? (Looking back through the 
> mailing list Greg did seem supportive.)
>

I have already started this.
Look at
https://github.com/mrkraimer/exampleJava
I still have some changes I have not committed but what is committed and 
pushed is a start.

My plans are:

After exampleCPP is merged into epics-base I plan to
1) remove examples from pvDatabaseCPP and also have a src/pv directory 
for all the include files
2) remove example from pvaClientCPP (it does not need a src/pv directory)
I have done 1) and 2) in my working area but need to do some more 
testing before pushing and issuing a pull request for epics_base.

After this I plan to finish exampleJava

Marty

**Comment by dhickin** [comment]
<p>I though the agreement was for Michael to generate the pull request for pvDataCPP (which he has done, <a href="https://github.com/epics-base/pvDataCPP/pull/19">pull #19</a>) and then we'd discuss whether to make the move (presumably at a telecon) and if so then do the move for the other modules.</p>

**Comment by mrkraimer** [comment]
On 01/13/2016 08:50 AM, dhickin wrote:
>
> I though the agreement was for Michael to generate the pull request 
> for pvDataCPP (which he has done, pull #19 
> <https://github.com/epics-base/pvDataCPP/pull/19>) and then we'd 
> discuss whether to make the move (presumably at a telecon) and if so 
> then do the move for the other modules.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/3#issuecomment-171296476>.
>
I thought that this pull request was already merged.
I see that this is not true.

I also see that there are 3 open pull requests for pvDataCPP.
The oldest is Dec 14, 2015
The newest is 26 days ago.

Somehow we need to be able to resolve these in a more timely manner.

Marty

**Comment by ralphlange** [comment]
Note that there were no telecons between Dec 15 and yesterday, and approx. two weeks of vacation.
As the default for non-trivial changes is to wait for at least one telecon to discuss them, this was perfectly according to schedule.

If we have things to discuss, we shouldn't cancel telecons. That would also help keeping them short.

**Comment by ralphlange** [comment]
@mrkraimer: Pull requests are between branches. Any pushes to the source branch of the request become part of it.

They show up in the web page when they happen, i.e. between comments.
Further up, you can see one just above your question ;-)

**Comment by dhickin** [comment]
Am I right in thinking that adding to the branch will not cause the automated tests to be run, but adding a comment saying “retest this” will redo the tests?

Presumably Marty should do this when he adds commits or the reviewer before the merge?

**Comment by ralphlange** [comment]
Compilation and tests are automagically re-run. (Results are shown on the right side of the additional commit.)

Manual "retest this please" is only necessary if a failure on the Jenkins side or something else requires re-running the tests without a commit.

**Comment by ralphlange** [comment]
LOL.
My last comment just started Jenkins. (The "please" is obviously required...)

**Comment by dhickin** [comment]
Marty, I see you commented that you were still having problems with the jenkins issue. Did you see my earlier comment on fixing this?

I don't think commit e7292e73e78a80db8828276f1189d04434e1f1ad is necessary. I'd reverse the change and try my fix.

**Comment by gregoryraymondwhite** [comment]
Yes, +1 to these points, particularly 2 and 3. I’m ok with the rearrangement of exampleJava. I’d 
just like the outcome to reflect the sort of thinking you made in your points 2 and 3 - only tests
should be called “test”, and all examples should be properly named consciously of their scope.

Good idea. Let’s add this to next week’s meeting.

Greg

**Comment by mrkraimer** [comment]
On 01/13/2016 11:33 AM, dhickin wrote:
>
> Marty, I see you commented that you were still having problems with 
> the jenkins issue. Did you see my earlier comment on fixing this?
>

Andrew,

Davids previous comment said:

I think you just need the change

-make -C HelloWorld distclean all
+make distclean all

in jenkins/cloudbees_build.



I agree that this change should definitely be made.


> I don't think commit e7292e7 
> <https://github.com/epics-base/exampleCPP/commit/e7292e73e78a80db8828276f1189d04434e1f1ad> 
> is necessary. I'd reverse the change and try my fix.
>

With either the old Makefile or the current version:
make distclean
Does NOT do a
perl /home/install/epics/base-3.14.12.5/bin/linux-x86_64/cvsclean in all 
the examples.

The current version does do it but only in the first example which is 
database.
It should.


Andrew may know how to fix the problem.

Marty

**Comment by mrkraimer** [comment]
I committed a change to jenkins/cloudbees_build
"retest this please" 
I want to see if this message makes jenkins rerun the test
Marty

**Comment by mrkraimer** [comment]
So the change to  jenkins/cloudbees_build did NOT fix the problem.
But I do not see anything that says why.

What to do?

**Comment by dhickin** [comment]
<p>It hasn't fixed it but you have moved forward.</p>

<p>Previously it was trying to build a target that didn't exist via</p>
<code>make -C HelloWorld distclean all</code>

<p>Now it's building the new top-level target and it failing because it can't find pvDatabase.a, so now you need to fix this.</p>

<p>See the <a href="https://openepics.ci.cloudbees.com/job/exampleCPP_PullRequests/BASE=3.16.DEV,USE_MB=MB_NO/6/console" >cloudbees job</a>.</p>

**Comment by ralphlange** [comment]
As I commented yesterday:

> **Compilation and tests are automagically re-run. (Results are shown on the right side of the additional commit.)**

> **Manual "retest this please" is only necessary if a failure on the Jenkins side or something else requires re-running the tests without a commit.**

**Comment by ralphlange** [comment]
The module seems to add a dependency on pvDatabaseCPP, which is not configured in the jenkins job.

**Comment by dhickin** [comment]
<p>Presumably Marty just needs to add</p>
<code>wget -nv https://openepics.ci.cloudbees.com/job/pvDatabaseCPP_${PVDATABASE_BRANCH}Build/BASE=${BASE},USE_MB=${USE_MB}/lastSuccessfulBuild/artifact/pvDatabase.CB-dist.tar.gz</code>
<p>to cloudbees_build to fix this.</p>

<p>I guess it also needs the equivalents for pvaClientCPP and normativeTypesCPP too.</p>

**Comment by ralphlange** [comment]
Here's a fix. (Use "git apply" to apply.)

[0001-jenkins-add-dependency-to-pvDatabaseCPP.zip](https://github.com/epics-base/exampleCPP/files/90410/0001-jenkins-add-dependency-to-pvDatabaseCPP.zip)

**Comment by ralphlange** [comment]
Oh, more dependencies.
Yes, they will need to be added, too.

**Comment by ralphlange** [comment]
The URL for fetching pvaSrv is wrong. The build part is `pvaSrvCPP_Build`.

**Comment by mrkraimer** [comment]
On 01/14/2016 07:28 AM, Ralph Lange wrote:
>
> As I commented yesterday:
>
>     *Compilation and tests are automagically re-run. (Results are
>     shown on the right side of the additional commit.)*
>
>     *Manual "retest this please" is only necessary if a failure on the
>     Jenkins side or something else requires re-running the tests
>     without a commit.*
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/3#issuecomment-171631623>.
>


I did make more changes to jenkins/cloudbees_build
Since this is only a change to jenkins it does seem that
"retest this please"
is needed to make it retest.

**Comment by ralphlange** [comment]
No. Any commit will trigger a test.

**Comment by ralphlange** [comment]
Your "change to jenkins" is a change in the jenkins directory of the code.

What I meant with "change to jenkins" is a change in the configuration of the job on the CloudBees jenkins server.

Your mention of the "re ...." plhrase triggered a rebuild before you pushed the change.

**Comment by ralphlange** [comment]
Dependencies look good now. At least we're getting further.

This time, the `RELEASE` file in `exampleRPCService` is crap and needs to be adapted to the new layout.

**Comment by dhickin** [comment]
Agree.I guess this is because exampleServiceRPC is a later addition.

Same applies for CONFIG_SITE.local. One include in the one in exampleRPCService doesn't exist and it has only 1 of the 3 includes in the other CONFIG_SITEs. Also CROSS_COMPILER_TARGET_ARCHS is set inconsistently.

Personally I wouldn't set CROSS_COMPILER_TARGET_ARCHS here - the other modules don't. I'd have it set in a CONFIG_SITE.local. I supply a top-level CONFIG_SITE.local in the bundle for this purpose.

I'd also set CHECK_RELEASE = YES

**Comment by mrkraimer** [comment]
Thanks to help from Ralph and David (especially from David in some private email) 
exampleCPP/jenkins/cloudbees_build
now works.

But there are still two problems:
1)  exampleCPP/exampleRPCService is not being built from the top level Makefile.
It it is jenkins fails.
This was in the original exampleCPP and I made almost no modifications to it.
I will let David take a look after the pull request is merged
2) executing make distclean  only does a
perl /home/install/epics/base-3.14.12.5/bin/linux-x86_64/cvsclean.pl
In the first example, which is database.
This means that make clean is done in all examples but make unisntall
I will ask Andrew to look at the top level Makefile after the pull request is merged

**Comment by dhickin** [comment]
> "This [exampleRPCService] was in the original exampleCPP and I made almost no modifications to it."

This is not correct. exampleRPCService is a recent addition to pvDatabaseCPP (it was the example of RPC functionality added to pvDatabaseCPP). Because of this it may have missed getting the changes that the other pvDatabase example got to adapt to the new structure. helloRPC and ChannelArchiverService are the old examples.

Can you fix the exampleServiceRPC RELEASE and CONFIG_SITE files (and any other files in configure). It should be a matter of making them the same as the other examples from pvDatabaseCPP. Should be trivial in a merge tool.

**Comment by mrkraimer** [comment]
On 01/14/2016 10:34 AM, Ralph Lange wrote:
>
> Dependencies look good now. At least we're getting further.
>
> This time, the |RELEASE| file in |exampleRPCService| is crap and needs 
> to be adapted to the new layout.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/3#issuecomment-171675326>.
>

Sorry I made my previous commit before looking at latest messages.

I did as you suggested and now it works with |exampleRPCService

Thanks




|

**Comment by anjohnson** [comment]
I suspect the problem is because the EPICS build rules were designed to have a configure directory at the top level, but your top Makefile is using the one in the database subdirectory. I'm looking at this right now so if you can wait I may be able to give you a fix fairly soon.

One thing that I've already noticed: The database/configure/ExampleRELEASE.local file has the lines in almost exactly the reverse order that they should be; `EPICS_BASE` should always come **last** in a RELEASE file, with `PVCOMMON` immediately above it and so on. If you copied this file from another module, that module also has it wrong and should be fixed too…

**Comment by anjohnson** [comment]
I have a fix for your `make distclean` issue, but the test sub-module could use some reorganization.

The rule for distclean first recursively runs `make realclean` in all subdirs, then it does a single `make cvsclean` from the top level (which descends into the sub-directories internally, you don't see it doing that), and finally it does a `make realuninstall` to remove the $(TOP)/bin and $(TOP)/lib directories (which in this case will actually be the ones in the database sub-directory since that's where you pointed TOP).

I assume you would like the `make realuninstall` to recursively descend into all the sub-modules, not just in the database module. That behavior is provided by a modified configure/RULES_TOP file that you need to copy from the pvaSrv/configure directory into your database/configure directory (it doesn't need to be present in the other modules, just in the one that you're using as TOP). You also need to modify your top-level Makefile to use it; just replace the contents of the top-level Makefile with this:

``` Makefile
# Makefile for the EPICS V4 exampleCPP module

TOP = ./database
include $(TOP)/configure/CONFIG

# No configure directory here

EMBEDDED_TOPS += $(TOP)/../database
EMBEDDED_TOPS += $(TOP)/../exampleClient
EMBEDDED_TOPS += $(TOP)/../exampleLink
EMBEDDED_TOPS += $(TOP)/../powerSupply
EMBEDDED_TOPS += $(TOP)/../helloPutGet
EMBEDDED_TOPS += $(TOP)/../helloRPC
EMBEDDED_TOPS += $(TOP)/../exampleRPCService
EMBEDDED_TOPS += $(TOP)/../arrayPerformance

DIRS += $(TOP)/../test
DIRS += $(EMBEDDED_TOPS)

# No inter-module dependencies

include $(TOP)/configure/RULES_TOP
```

With the above changes, you could merge this pull request, although I don't think we're completely done with exampleCPP quite yet. The reason that the test module is handled differently above than all of the others is because it's a bit of a Frankenstein monster.

The test subdirectory has its own configure directory and the Makefile sets `TOP = .` but then the Makefile actually compiles code and ends with `include $(TOP)/configure/RULES` so it's not really a top Makefile and it can't actually support the standard top-level build targets such as `make distclean` that you get by including the RULES_TOP file. The compilation parts need to be moved into a src subdirectory, and a proper top Makefile used instead. The module name should also be changed, this is really pvaClientTest isn't it? Once that has been done that it can be added to the Makefile's EMBEDDED_TOPS list like all the other modules above.

**Comment by dhickin** [comment]
I'd like to see the issues I raised above with respect to directory names resolved before a merge. We could merge first and fix separately, but why not do it now?

In particular "test" cannot be called "test"  and "exampleRPCService" is extremely confusing.

The directory called "test" is a pvaClient test/example and should reference pvaClient or have some meaningful name.

The directory called exampleRPCService contains an example of a  pvDatabase PVRecord that also supports RPC and so must reference pvDatabase or given a meaning based on the functionality e.g. "position". (I prefer the former). Otherwise someone looking for how to write an RPC service will end up basing it on at exampleRPCService (wouldn't you?) and that would likely be the wrong thing to do.

So e.g.
test->pvaClient
exampleRPCService->pvDatabaseRPC

Also, I've checked and  all the ExampleRELEASE.local's define their variables in reverse order to what they should (except for ChannelArchiverService, which doesn't have one).

**Comment by anjohnson** [comment]
I agree that it would be better to fix David's issues properly before merging, although there are so many changes in this branch now that github can't actually display the differences, which makes it hard to review them as a single unit.

**Comment by mrkraimer** [comment]
On 01/15/2016 12:57 PM, Andrew Johnson wrote:
>
> I have a fix for your |make distclean| issue, but the test sub-module 
> could use some reorganization.
>
> The rule for distclean first recursively runs |make realclean| in all 
> subdirs, then it does a single |make cvsclean| from the top level 
> (which descends into the sub-directories internally, you don't see it 
> doing that), and finally it does a |make realuninstall| to remove the 
> $(TOP)/bin and $(TOP)/lib directories (which in this case will 
> actually be the ones in the database sub-directory since that's where 
> you pointed TOP).
>
> I assume you would like the |make realuninstall| to recursively 
> descend into all the sub-modules, not just in the database module. 
> That behavior is provided by a modified configure/RULES_TOP file that 
> you need to copy from the pvaSrv/configure directory into your 
> database/configure directory (it doesn't need to be present in the 
> other modules, just in the one that you're using as TOP). You also 
> need to modify your top-level Makefile to use it; just replace the 
> contents of the top-level Makefile with this:
>
> # Makefile for the EPICS V4 exampleCPP module
>
> TOP  = ./database
> include  $(TOP)/configure/CONFIG
>
> # No configure directory here
>
> EMBEDDED_TOPS  +=$(TOP)/../database
> EMBEDDED_TOPS  +=$(TOP)/../exampleClient
> EMBEDDED_TOPS  +=$(TOP)/../exampleLink
> EMBEDDED_TOPS  +=$(TOP)/../powerSupply
> EMBEDDED_TOPS  +=$(TOP)/../helloPutGet
> EMBEDDED_TOPS  +=$(TOP)/../helloRPC
> EMBEDDED_TOPS  +=$(TOP)/../exampleRPCService
> EMBEDDED_TOPS  +=$(TOP)/../arrayPerformance
>
> DIRS  +=$(TOP)/../test
> DIRS  +=$(EMBEDDED_TOPS)
>
> # No inter-module dependencies
>
> include  $(TOP)/configure/RULES_TOP
>
> With the above changes, you could merge this pull request, although I 
> don't think we're completely done with exampleCPP quite yet. The 
> reason that the test module is handled differently above than all of 
> the others is because it's a bit of a Frankenstein monster.
>
> The test subdirectory has its own configure directory and the Makefile 
> sets |TOP = .| but then the Makefile actually compiles code and ends 
> with |include $(TOP)/configure/RULES| so it's not really a top 
> Makefile and it can't actually support the standard top-level build 
> targets such as |make distclean| that you get by including the 
> RULES_TOP file. The compilation parts need to be moved into a src 
> subdirectory, and a proper top Makefile used instead. The module name 
> should also be changed, this is really pvaClientTest isn't it? Once 
> that has been done that it can be added to the Makefile's 
> EMBEDDED_TOPS list like all the other modules above.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/3#issuecomment-172034506>.
>
Thanks!!

I have made all the changes you suggested and also changed all the 
ExampleRELEASE.local files.
make distclean
now works from the top level.

I am not sure what to do about the test submodule.
Note that it is not quite the same as pvaClientTest because 
pvaClientTest built the database as well as test.

test could be changed to not have all the source files at the top level 
but in some subdirectory.
If so I suggest the subdirectory be named test.

**Comment by mrkraimer** [comment]
On 01/15/2016 01:36 PM, dhickin wrote:
>
> I'd like to see the issues I raised above with respect to directory 
> names resolved before a merge. We could merge first and fix 
> separately, but why not do it now?
>
> In particular "test" cannot be called "test" and "exampleRPCService" 
> is extremely confusing.
>
> The directory called "test" is a pvaClient test/example and should 
> reference pvaClient or have some meaningful name.
>

I made a comment about test in my reply to andrew.
I don't know what should be done.


> The directory called exampleRPCService contains an example of a 
> pvDatabase PVRecord that also supports RPC and so must reference 
> pvDatabase or given a meaning based on the functionality e.g. 
> "position". (I prefer the former). Otherwise someone looking for how 
> to write an RPC service will end up basing it on at exampleRPCService 
> (wouldn't you?) and that would likely be the wrong thing to do.
>
exampleRPCService is adapted from code you wrote, but I do not remember 
where I copied it from

It is run as follows:
mrk> pwd
bin/linux-x86_64/exampleRPCMain

Then in another window:
mrk> pvget -m mydevice
mydevice
structure
     double x 0
     double y 0
     time_t timeStamp <undefined> 0

Then in yet another window:

mrk> pwd
/home/epicsv4/master/exampleCPP/exampleRPCService
mrk> bin/linux-x86_64/move 1 2 3 4


The monitor then shows:

mydevice
structure
     double x 1
     double y 2
     time_t timeStamp 2016-01-18T11:21:51.267 0


mydevice
structure
     double x 3
     double y 4
     time_t timeStamp 2016-01-18T11:21:52.267 0

I will let you decide how exampleRPCService should be changed.


> So e.g.
> test->pvaClient
> exampleRPCService->pvDatabaseRPC
>
> Also, I've checked and all the ExampleRELEASE.local's define their 
> variables in reverse order to what they should
>

All changed.

> (except for ChannelArchiverService, which doesn't have one).
>

ChannelArchiverService is from your original code in exampleCPP.
I left it out of the top level make file with the intention of letting 
you decide how it should be changed.

**Comment by mrkraimer** [comment]
On 01/15/2016 01:44 PM, Andrew Johnson wrote:
>
> I agree that it would be better to fix David's issues properly before 
> merging, although there are so many changes in this branch now that 
> github can't actually display the differences, which makes it hard to 
> review them as a single unit.
>

Yes it is!!!

So can we now merge?

Then it will be easier to understand changes andlet others instead of 
just me make changes.

**Comment by dhickin** [comment]
exampleRPCService was copied from pvDatabaseCPP/exampleRPC. This was an example I added when I added RPC to pvDatabseCPP.

It must, for the reasons I've stated, be renamed, preferably to reference pvDatabase, e.g. pvDatabaseRPC.

test could be renamed pvaClientTest if it's test code or either pvaClientExample or just pvaClient if it's an example. (It mostly seems to be pvaClient code, so those names make sense to me).

I do suggest we make these two changes first.

If it's getting hard to review changes we could consider a fresh branch/pull request with a cleaned up commit history. I don't mind either way from  a point of view of reviewing the code - I think it's sufficiently easy to review the changes as is and the directory name changes are easy to understand. However it may be easier for people to follow the commit history in future if we do clean up.

**Comment by anjohnson** [comment]
Why did you add the test module to exampleCPP in the first place? It does seem a bit out of place.

In the Release Notes for pvaClientTestCPP version 4.5 I see the statement
> This is the first release of pvaClientTestCPP.
> It will also be the last because it will be replaced by pvExampleTestCPP.
I'm not sure that I agree with that last statement; Isn't the point of this module to provide an automated integration test of a pvaClient application connecting to a pvDatabase server? If that is true then it shouldn't be disappearing into a C++ examples module, but should instead be part of a separate high-level integration testing module.

@dhickin The github problem isn't that the git history is convoluted, I think it's just the sheer volume of changes that appear in this one merge request. To clean up properly I think it would be necessary to split the changes into multiple merge requests, say one merge per sub-module. I'm not sure that we want to ask Marty to do that much extra work, although I expect a git expert like @mdavidsaver might be able to do such a split relatively efficiently if he had the time.

**Comment by mrkraimer** [comment]
On 01/18/2016 11:52 AM, dhickin wrote:
>
> exampleRPCService was copied from pvDatabaseCPP/exampleRPC. This was 
> an example I added when I added RPC to pvDatabseCPP.
>
> It must, for the reasons I've stated, be renamed, preferably to 
> reference pvDatabase, e.g. pvDatabaseRPC.
>
> test could be renamed pvaClientTest if it's test code or either 
> pvaClientExample or just pvaClient if it's an example. (It mostly 
> seems to be pvaClient code, so those names make sense to me).
>
> I do suggest we make these two changes first.
>

I suggest we merge first.
Then you can fork and make changes to exampleRPC and to 
ChannelArchiverService.

**Comment by mrkraimer** [comment]
On 01/18/2016 12:06 PM, Andrew Johnson wrote:
>
> Why did you add the test module to exampleCPP in the first place? It 
> does seem a bit out of place.
>
> In the Release Notes for pvaClientTestCPP version 4.5 I see the statement
>
>     This is the first release of pvaClientTestCPP.
>     It will also be the last because it will be replaced by
>     pvExampleTestCPP.
>     I'm not sure that I agree with that last statement; Isn't the
>     point of this module to provide an automated integration test of a
>     pvaClient application connecting to a pvDatabase server? If that
>     is true then it shouldn't be disappearing into a C++ examples
>     module, but should instead be part of a separate high-level
>     integration testing module.
>

That was before the idea of putting all the examples from pvaClientCPP 
and pvDatabaseCPP into exampleCPP.
If test is also moved from pvaClientTestCPP then pvaClientTestCPP is no 
longer needed.

The test is really important because it uses parts of all of pvDataCPP, 
normativeTypesCPP, pvAccessCPP, pvaSrv, pvDatabaseCPP, and pvaClientCPP.

**Pull request merged**
