### PR TITLE
Many minor changes including documentation

### PR DESCRIPTION
**Pull request by mrkraimer**
As the title says many minor changes including

1) update documentation including all example doc.
2) Make termination more consistent between examples.

Unless I hear otherwise I will merge tomorrow.

### CODE REVIEW

**Comment by dhickin** [comment]
Marty, can you <b>hold</b> merging this. I was out the office at a Diamond event yesterday, but I'd like to take a look at it. I'll do this now.

**Comment by mrkraimer** [comment]
On 02/26/2016 04:54 AM, dhickin wrote:
>
> Marty, can you *hold* merging this. I was out the office at a Diamond 
> event yesterday, but I'd like to take a look at it. I'll do this now.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/7#issuecomment-189199436>.
>
OK.

Send another message after you take a look or if you want just merge.

Marty

**Comment by dhickin** [comment]
Marty, I've had a look a the changes and the current state of exampleCPP. Comments below. Note I realise it's work in progress so these shouldn't in most cases gate the merge. However can you take a look at 1 and 2 and decide what to do

1) arrayPerformance

When I ran the default arrayPerformance application it exited with an exception:

"exception channel arrayPerformance PvaClientChannel::connect arrayPerformance createChannel failed"

If you run with monitors set to 0, e.g.

./bin/linux-x86_64/arrayPerformanceMain arrayPerformance 10000000 0.0001 local 0 2

 it runs OK.
 
However a pvget fails, first with a timeout, then with an exception (after a timeout)

$pvget arrayPerformance
[arrayPerformance] get timeout
$ pvget arrayPerformance
[arrayPerformance] get timeout
2016-02-29T11:38:11.858 Unhandled exception caught from client code at ../../src/remoteClient/clientContextImpl.cpp:270: bytesRead < 0

With a smaller array size (e.g. 3000000) the pvget succeeds. At the default size monitor behaviour is also strange: only intermittent updates and I think one lock up server-side.

2) The powerSupply client example exited with an exception:

PvaClientPutGet::putGet bad voltage exception

I haven't looked any further yet as to why. I may be doing something wrong, however the client doesn't take an argument and I'm following the instructions.

3) All the READMEs tell you to type

    edit configure/RELEASE.local

Better to tell the user to edit the file - edit might not be a command on their system (it isn't on mine). Also perhaps describe how they should edit the RELEASE.local

4) I think all the examples can be built by providing a RELEASE.local in 1 of

a) the parent directory of exampleCPP
b) the configure directory of exampleCPP
c) the configure directory of each example

but the instructions mention only a) and c)
b) is useful as it allows you to specify the RELEASE.local in a single place. a) won't always be an option (we can't have a top-level RELEASE.local and use our current iocbuilder).

5) The READMEs could do with instructions for running in some cases. (If you intend to add them later that's fine - it certainly shouldn't prevent a merge. It's just a comment).

6) Definitely need instructions for the database example client-side. It's not obvious how to access the different types of services available. In particular the helloRPC service in database has a different name and different structure to the one in helloRPC, so the client included in helloRPC certainly can't be used. The only way I could find to access the service was eget with the -z option

eget -N -z -a "value=Dave" -s helloRPC

which is hard for people to find.

7) helloPutGet

I would change this so you can add an argument in the client (e.g. a name like in helloRPC). Then you can see your value come back and try multiple values.

8) You've added README.mds to helloRPC and the Channel Archiver service. Note these already have their own READMEs. They should probably be combined. I can do this if you want. I'll just have to update the build instructions. If you want to do this then please keep the bulk of the quite detailed instructions that are already there.

9) There are quite a few references to linux-x86_64 in running examples. These should probably be $EPICS_HOST_ARCH.

**Comment by mrkraimer** [comment]
On 02/29/2016 07:37 AM, dhickin wrote:
>
> Marty, I've had a look a the changes and the current state of 
> exampleCPP. Comments below. Note I realise it's work in progress so 
> these shouldn't in most cases gate the merge. However can you take a 
> look at 1 and 2 and decide what to do
>
> 1) arrayPerformance
>
> When I ran the default arrayPerformance application it exited with an 
> exception:
>
> "exception channel arrayPerformance PvaClientChannel::connect 
> arrayPerformance createChannel failed"
>
> If you run with monitors set to 0, e.g.
>
> ./bin/linux-x86_64/arrayPerformanceMain arrayPerformance 10000000 
> 0.0001 local 0 2
>
> it runs OK.
>

I am wondering if it is a memory problem.
Does it work with?
./bin/linux-x86_64/arrayPerformanceMain arrayPerformance 1000000
Can you start the linux System Monitor and look at memory usage while 
starting arrayPerformanceMain?

Also I am working on implementing arrayPerformance in exampleJava.
While doing this I see many places to make minor improvements to 
exampleCPP/arrayPerformance.
But I am not quite ready to push the changes.
I have all the arrayPerformence tests running on both CPP and Java.
But I want to look carefully at the code once more before pushing.
I will do this before making any changes for the other examples that You 
discuss below.

> However a pvget fails, first with a timeout, then with an exception 
> (after a timeout)
>
> $pvget arrayPerformance
> [arrayPerformance] get timeout
> $ pvget arrayPerformance
> [arrayPerformance] get timeout
> 2016-02-29T11:38:11.858 Unhandled exception caught from client code at 
> ../../src/remoteClient/clientContextImpl.cpp:270: bytesRead < 0
>
> With a smaller array size (e.g. 3000000) the pvget succeeds. At the 
> default size monitor behaviour is also strange: only intermittent 
> updates and I think one lock up server-side.
>

Note that pvget is attempting to print a VERY large array.
Again can it be a memory problem?


> 2) The powerSupply client example exited with an exception:
>
> PvaClientPutGet::putGet bad voltage exception
>
> I haven't looked any further yet as to why. I may be doing something 
> wrong, however the client doesn't take an argument and I'm following 
> the instructions.
>

This is done on purpose to tests if exceptions are handled properly.
Note that the process method is:

void PowerSupply::process()
{
     timeStamp.getCurrent();
     pvTimeStamp.set(timeStamp);
     double voltage = pvVoltage->get();
     double power = pvPower->get();
     if(voltage<1e-3 && voltage>-1e-3) {
         alarm.setMessage("bad voltage");
         alarm.setSeverity(majorAlarm);
         pvAlarm.set(alarm);
         throw std::runtime_error("bad voltage exception");
     }
     double current = power/voltage;
     pvCurrent->put(current);
     alarm.setMessage("");
     alarm.setSeverity(noAlarm);
     pvAlarm.set(alarm);
}

Note in particular throw std::runtime_error("bad voltage exception");
The exception does get all the way back to the client.

> 3) All the READMEs tell you to type
>
> |edit configure/RELEASE.local |
>
> Better to tell the user to edit the file - edit might not be a command 
> on their system (it isn't on mine). Also perhaps describe how they 
> should edit the RELEASE.local
>

OK I will correct the documentation

> 4) I think all the examples can be built by providing a RELEASE.local 
> in 1 of
>
> a) the parent directory of exampleCPP
> b) the configure directory of exampleCPP
> c) the configure directory of each example
>
> but the instructions mention only a) and c)
> b) is useful as it allows you to specify the RELEASE.local in a single 
> place. a) won't always be an option (we can't have a top-level 
> RELEASE.local and use our current iocbuilder).
>

OK I will correct the documentation.
>
> 5) The READMEs could do with instructions for running in some cases. 
> (If you intend to add them later that's fine - it certainly shouldn't 
> prevent a merge. It's just a comment).
>
> 6) Definitely need instructions for the database example client-side. 
> It's not obvious how to access the different types of services 
> available. In particular the helloRPC service in database has a 
> different name and different structure to the one in helloRPC, so the 
> client included in helloRPC certainly can't be used. The only way I 
> could find to access the service was eget with the -z option
>
> eget -N -z -a "value=Dave" -s helloRPC
>
> which is hard for people to find.
>
> 7) helloPutGet
>
> I would change this so you can add an argument in the client (e.g. a 
> name like in helloRPC). Then you can see your value come back and try 
> multiple values.
>
> 8) You've added README.mds to helloRPC and the Channel Archiver 
> service. Note these already have their own READMEs. They should 
> probably be combined. I can do this if you want. I'll just have to 
> update the build instructions. If you want to do this then please keep 
> the bulk of the quite detailed instructions that are already there.
>
> 9) There are quite a few references to linux-x86_64 in running 
> examples. These should probably be $EPICS_HOST_ARCH.
>

I will make the change for 9)

For 5, 6, 7, 8 I will not make any changes until after I merge 1, 3,4, 
and 9.
The maybe we can decide how to divide the work?

Does this all seem OK with you?

Marty

**Comment by dhickin** [comment]
>Does it work with?
> ./bin/linux-x86_64/arrayPerformanceMain arrayPerformance 1000000

No I get the same exception regardless of the value of "size" when nMonitor > 0.

> This is done on purpose to tests if exceptions are handled properly.
I see. But this isn't obvious if you've just got exampleCPP and are trying the examples. A user might just think something had failed unexpectedly (as I did). Some words outputted to prime them that the exception is expected would help. A better example might be taking an argument for the voltage and the client code describes what's expected to happen based on the value and then says what actually happens. Then people can play.

> Does this all seem OK with you?
Fine by me.

**Comment by gregoryraymondwhite** [comment]
I remember the same problems in v4 years ago - that test cases that test exception handling without any indication to a user that the correct behavior is exception.  

Can we have a pattern for tests where those testing exception handling are clearly indicated in a consistent way across modules?

Greg

**Comment by mrkraimer** [comment]
latest commit to mrkraimer includes the following changes:

1)  arrayPerformance has many minor changes resulting from
working on exampleJava/arrayPerformance

2) All the README.md files that have build instructions have been revised to try to
satisfy 3) and 4) of Davids message above.

3) powerSupply now gives a notice that setting the voltage to 0 will cause an exception.

4) Wherever linux-x86_64 appears in .md or .html files it is replaced by $EPICS_HOST_ARCH.

This I think I have done 1, 2, 3, 4, and 9 of David's original message.

But for 1 I need David to again test.

**Comment by dhickin** [comment]
<p>I tried the latest and the exception in arrayPerformanceMain still happens, but now is uncaught:</p>

<code>
epicsThread: Unexpected C++ exception "channel arrayPerformance PvaClientChannel::connect arrayPerformance createChannel failed" with type "St13runtime_error" in thread "longArrayMonitor" at Wed Mar 02 2016 00:41:18.719722233</code>
<code>terminate called after throwing an instance of 'std::runtime_error'
  what():  channel arrayPerformance PvaClientChannel::connect arrayPerformance createChannel failed
Aborted (core dumped)
</code>
<p>I tried creating the monitors with the providerName="pva" instead of "local" and the exception doesn't occur. (The overrun bits are set though - {1, 2}.)</p>

Do you see the same issue? If not which versions of dependent modules are you using? I'm using up-to-date master on all other modules and R3.14.12.3.

**Comment by mrkraimer** [comment]
On 03/01/2016 08:19 PM, dhickin wrote:
>
> I tried the latest and the exception in arrayPerformanceMain still 
> happens, but now is uncaught:
>
> |
> epicsThread: Unexpected C++ exception "channel arrayPerformance 
> PvaClientChannel::connect arrayPerformance createChannel failed" with 
> type "St13runtime_error" in thread "longArrayMonitor" at Wed Mar 02 
> 2016 00:41:18.719722233|
> |terminate called after throwing an instance of 'std::runtime_error'
> what(): channel arrayPerformance PvaClientChannel::connect 
> arrayPerformance createChannel failed
> Aborted (core dumped)
> |
>
> I tried creating the monitors with the providerName="pva" instead of 
> "local" and the exception doesn't occur. (The overrun bits are set 
> though - {1, 2}.)
>

This is expected
>
> Do you see the same issue? If not which versions of dependent modules 
> are you using? I'm using up-to-date master on all other modules and 
> R3.14.12.3.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/7#issuecomment-191005227>.
>

I am building against latest version of the following

_________________start___________
_________________ + /home/epicsv4/master/pvCommonCPP + ___________

[remote "origin"]
     url = https://github.com/epics-base/pvCommonCPP.git
     fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]

_________________ + /home/epicsv4/master/pvDataCPP + ___________

[remote "origin"]
     url = https://github.com/epics-base/pvDataCPP.git
     fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]

_________________ + /home/epicsv4/master/normativeTypesCPP + ___________

[remote "origin"]
     url = https://github.com/epics-base/normativeTypesCPP.git
     fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]

_________________ + /home/epicsv4/master/pvAccessCPP + ___________
[core]

[remote "origin"]
     url = https://github.com/msekoranja/pvAccessCPP-md
     fetch = +refs/heads/*:refs/remotes/origin/*
[branch "broken"]

_________________ + /home/epicsv4/master/pvaClientCPP + ___________
[core]

[remote "origin"]
     url = https://github.com/mrkraimer/pvaClientCPP.git
     fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]

_________________ + /home/epicsv4/master/pvaSrv + ___________
[core]

[remote "origin"]
     url = https://github.com/mrkraimer/pvaSrv.git
     fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]

_________________ + /home/epicsv4/master/pvDatabaseCPP + ___________
[core]

[remote "origin"]
     url = https://github.com/mrkraimer/pvDatabaseCPP.git
     fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]

_________________ + /home/epicsv4/master/exampleCPP + ___________
[core]

[remote "origin"]
     url = https://github.com/mrkraimer/exampleCPP.git
     fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]

**Comment by dhickin** [comment]
<blockquote>@mrkaraimer: I am building against latest version of the following:<br/><br/>

url = https://github.com/epics-base/pvCommonCPP.git [branch "master"]<br/>
url = https://github.com/epics-base/pvDataCPP.git [branch "master"]<br/>
url = https://github.com/epics-base/normativeTypesCPP.git [branch "master"]<br/>
url = https://github.com/msekoranja/pvAccessCPP-md [branch "broken"]<br/>
url = https://github.com/mrkraimer/pvaClientCPP.git [branch "master"]<br/>
url = https://github.com/mrkraimer/pvaSrv.git [branch "master"]<br/>
url = https://github.com/mrkraimer/pvDatabaseCPP.git [branch "master"]<br/>
url = https://github.com/mrkraimer/exampleCPP.git [branch "master"]<br/>
</blockquote>

<p>I think you should really be trying the stuff you want to pull into the master branch of epics-base/exampleCPP against the master branches of the epics-base antecedents. That way what works for you has a good chance of working for everyone else.</p>

<p>I quickly tried your exampleCPP pull request against msekoranja/pvAccessCPP-md [branch "broken"] and mrkraimer/pvaClientCPP [branch "master"] and the arrayPerformance exception doesn't occur.I also tried your version of pvaClient with the epics-base master pvAccess and this worked for me too.</p>

<p>I see there are changes in your version of pvaClientChannel.cpp. When I try these in epics-base/pvaClientCPP the exception goes away.</p>

<p>I think you need to look at what's in your copy of pvaClientCPP and see whether anything needs to go into the epics-base version. I'd do that before we merge the exampleCPP changes.</p>

**Comment by mrkraimer** [comment]
On 03/02/2016 07:25 AM, dhickin wrote:
>
>     @mrkaraimer: I am building against latest version of the following:
>
>     url = https://github.com/epics-base/pvCommonCPP.git [branch "master"]
>     url = https://github.com/epics-base/pvDataCPP.git [branch "master"]
>     url = https://github.com/epics-base/normativeTypesCPP.git [branch
>     "master"]
>     url = https://github.com/msekoranja/pvAccessCPP-md [branch "broken"]
>     url = https://github.com/mrkraimer/pvaClientCPP.git [branch "master"]
>     url = https://github.com/mrkraimer/pvaSrv.git [branch "master"]
>     url = https://github.com/mrkraimer/pvDatabaseCPP.git [branch "master"]
>     url = https://github.com/mrkraimer/exampleCPP.git [branch "master"]
>
> I think you should really be trying the stuff you want to pull into 
> the master branch of epics-base/exampleCPP against the master branches 
> of the epics-base antecedents. That way what works for you has a good 
> chance of working for everyone else.
>
> I quickly tried your exampleCPP pull request against 
> msekoranja/pvAccessCPP-md [branch "broken"] and mrkraimer/pvaClientCPP 
> [branch "master"] and the arrayPerformance exception doesn't occur.I 
> also tried your version of pvaClient with the epics-base master 
> pvAccess and this worked for me too.
>
> I see there are changes in your version of pvaClientChannel.cpp. When 
> I try these in epics-base/pvaClientCPP the exception goes away.
>
> I think you need to look at what's in your copy of pvaClientCPP and 
> see whether anything needs to go into the epics-base version. I'd do 
> that before we merge the exampleCPP changes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/7#issuecomment-191220063>.
>
I merge a pull request for pvaClientCPP.
It had actually been created some time ago and I never merged it.

I am also now using epics-base master branch for pvAccessCPP because I 
see that Matej merged.

I will now try to see if base 3.15 works.

Marty

**Comment by dhickin** [comment]
<p>Great Marty, with the pvaClientCPP PR merged the exception arrayPerformance goes away. I've tried with Matej's latest pvAccess and all seems to be OK so far.</p>

<p>2 and 3 above have been addressed.</p>

<p>Re 4, what I said wasn't quite right.</p>

<p>The top-level RELEASE in exampleCPP/configure pulls in </p>
-include $(TOP)/../RELEASE.local
-include $(TOP)/configure/RELEASE.local
-include $(TOP)/RELEASE.local
 
<p>and each application pulls in </p>
-include $(TOP)/../../RELEASE.local
-include $(TOP)/../RELEASE.local
-include $(TOP)/configure/RELEASE.local
-include $(TOP)/../configure/RELEASE.local

<p>So in fact fact the README.md instructions aren't quite right yet, as they don't mention putting a RELEASE.local in exampleCPP/configure.</p>

<p>We could drop </p>
"-include $(TOP)/../RELEASE.local"
<p>from the application RELEASE and</p>
"-include $(TOP)/RELEASE.local"
<p>from the top-level as this may be overkill.</p>

<p>We'd still have to update the README.mds.</p>

<p>Note these</p>
-include $(TOP)/configure/RELEASE.local
-include $(TOP)/../configure/RELEASE.local

<p>are really in the wrong order it should be</p>

-include $(TOP)/../configure/RELEASE.local
-include $(TOP)/configure/RELEASE.local

<p>In the top-level README.md you have<p>

An example of a proper *RELEASE.local* is:

    EPICS_BASE=/home/install/epics/base
    EPICS4_DIR=/home/epicsv4/master
    PVCOMMON=${EPICS4_DIR}/pvCommonCPP
    PVDATA=${EPICS4_DIR}/pvDataCPP
    PVACCESS=${EPICS4_DIR}/pvAccessCPP
    PVASRV=${EPICS4_DIR}/pvaSrv
    NORMATIVETYPES=${EPICS4_DIR}/normativeTypesCPP
    PVDATABASE=${EPICS4_DIR}/pvDatabaseCPP
    PVACLIENT=${EPICS4_DIR}/pvaClientCPP

<p>This is really a reverse order. It's better to order these from most to least derived. The exampleRELEASE.local's have a better order.</p>

**Comment by mrkraimer** [comment]
On 03/02/2016 10:44 AM, dhickin wrote:
>
> Great Marty, with the pvaClientCPP PR merged the exception 
> arrayPerformance goes away. I've tried with Matej's latest pvAccess 
> and all seems to be OK so far.
>
> 2 and 3 above have been addressed.
>
> Re 4, what I said wasn't quite right.
>
> The top-level RELEASE in exampleCPP/configure pulls in
>
> -include $(TOP)/../RELEASE.local
> -include $(TOP)/configure/RELEASE.local
> -include $(TOP)/RELEASE.local
>
> and each application pulls in
>
> -include $(TOP)/../../RELEASE.local
> -include $(TOP)/../RELEASE.local
> -include $(TOP)/configure/RELEASE.local
> -include $(TOP)/../configure/RELEASE.local
>
> So in fact fact the README.md instructions aren't quite right yet, as 
> they don't mention putting a RELEASE.local in exampleCPP/configure.
>
> We could drop
>
> "-include $(TOP)/../RELEASE.local"
>
> from the application RELEASE and
>
> "-include $(TOP)/RELEASE.local"
>
> from the top-level as this may be overkill.
>
> We'd still have to update the README.mds.
>
> Note these
>
> -include $(TOP)/configure/RELEASE.local
> -include $(TOP)/../configure/RELEASE.local
>
> are really in the wrong order it should be
>
> -include $(TOP)/../configure/RELEASE.local
> -include $(TOP)/configure/RELEASE.local
>
> In the top-level README.md you have
>
> An example of a proper *RELEASE.local* is: 
> EPICS_BASE=/home/install/epics/base EPICS4_DIR=/home/epicsv4/master 
> PVCOMMON=${EPICS4_DIR}/pvCommonCPP PVDATA=${EPICS4_DIR}/pvDataCPP 
> PVACCESS=${EPICS4_DIR}/pvAccessCPP PVASRV=${EPICS4_DIR}/pvaSrv 
> NORMATIVETYPES=${EPICS4_DIR}/normativeTypesCPP 
> PVDATABASE=${EPICS4_DIR}/pvDatabaseCPP 
> PVACLIENT=${EPICS4_DIR}/pvaClientCPP
>
> This is really a reverse order. It's better to order these from most 
> to least derived. The exampleRELEASE.local's have a better order.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/7#issuecomment-191294136>.
>

I made all the changes and pushed to mrkraimer

**Comment by dhickin** [comment]
retest this please

**Comment by mrkraimer** [comment]
On 03/02/2016 09:04 PM, dhickin wrote:
>
> retest this please
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/7#issuecomment-191538198>.
>

I built against the latest pvaSrv and pvAccessCPP from master branch on 
epics-base

I ran the following three times and all were successful
mrk> pwd
/home/epicsv4/master/exampleCPP/test
mrk> make runtests

However when I run the following:

In one window

mrk> pwd
/home/epicsv4/master/exampleCPP/database/iocBoot/exampleDatabase
mrk> valgrind ../../bin/linux-x86_64/exampleDatabase st.cmd


And in another window:

mrk> pwd
/home/epicsv4/master/exampleCPP/exampleClient
mrk> bin/linux-x86_64/examplePvaClientNTMulti

It works sometimes but ultimately I get a crash in exampleDatabase.
valgrind shows.

epics> ==1604== Thread 35 TCP-rx:
==1604== Jump to the invalid address stated on the next line
==1604==    at 0x100000005ED1513: ???
==1604==    by 0xD90E6FF: ???
==1604==  Address 0x100000005ed1513 is not stack'd, malloc'd or 
(recently) free'd
==1604==
==1604==
==1604== Process terminating with default action of signal 11 (SIGSEGV)
==1604==  Bad permissions for mapped region at address 0x100000005ED1513
==1604==    at 0x100000005ED1513: ???
==1604==    by 0xD90E6FF: ???
==1604==


 From the name of the thread it looks like a pva thread.

I got the same thing with
mrk> bin/linux-x86_64/examplePvaClientMultiDouble
Same message from valgrind.

I had to run it many times before exampleDatabase crashed.

**Comment by dhickin** [comment]
I think this may be related to the issues I was reporting yesterday post the pvAccess merge. I’m in the process of opening up an issue for this.
I’ve only seen the issue affecting pvaSrv PVs (I was looking at the exampleCPP/database and testTop in pvaSrv). pvDatabase and RPC are unaffected as far as I know.

I suspect the issue is unrelated to the pull request.

Dave

**Comment by ralphlange** [comment]
It also seems to be missing the debugging symbols?!

**Pull request merged**
