### PR TITLE
test is no longer embeded; add SHRLIB_VERSION; add throw test;

### PR DESCRIPTION
**Pull request by mrkraimer**
test is no longer an embeded top.
This it is meant to be run via "make runtest"  in exampleCPP.

For all examples the src/Makefiles now have a definition for SHRLIB_VERSION.
Also all examples have a separate src/pv directory for the include files.

Example powerSupply now has an example that has a throw in process when voltage is near 0.

### CODE REVIEW

**Comment by mrkraimer** [comment]
Andrew,

Can I ask you to look at https://github.com/mrkraimer/exampleCPP
The failure is when jenkins builds test

Look at

https://openepics.ci.cloudbees.com/job/exampleCPP_PullRequests/BASE=3.14.12.5,USE_MB=MB_NO/15/console

I looked at exampleCPP/test/Makfile and can not see anything wrong.

Can You?

**Comment by ralphlange** [comment]
The include path for EPICS_BASE (/tmp/stuff/include) is missing.
All compile lines before have `-I/tmp/stuff/include/os/Linux -I/tmp/stuff/include`, the test stuff does not.

Are you resetting EPICS_BASE somewhere?

**Comment by mrkraimer** [comment]
On 01/27/2016 10:23 AM, Ralph Lange wrote:
>
> The include path for EPICS_BASE (/tmp/stuff/include) is missing.
> All compile lines before have |-I/tmp/stuff/include/os/Linux 
> -I/tmp/stuff/include|, the test stuff does not.
>

I do not understand.

Can you show me some console output?

Since test is no longer a an embedded top it uses from exampleCPP/configure

> Are you resetting EPICS_BASE somewhere?
>

Not as for as I know.

**Comment by mrkraimer** [comment]
I do not know how to make the checks succeed.
In my local area https://github.com/mrkraimer/exampleCPP.git works when I build against
base-3.14.12.5

But the jenkins build fails.

https://openepics.ci.cloudbees.com/view/EPICS%20V4%20C++/job/exampleCPP_PullRequests/17/BASE=3.14.12.5,USE_MB=MB_NO/console

Note that all embeded examples appear to build.
But when attempts to build test, which is no longer embeded it fails with:

make -C ./test install 
make[1]: Entering directory `/scratch/jenkins/workspace/exampleCPP_PullRequests/BASE/3.14.12.5/USE_MB/MB_NO/test'
perl /tmp/stuff/bin/linux-x86_64/makeMakefile.pl O.linux-x86_64 ../..
mkdir O.Common
make -C O.linux-x86_64 -f ../Makefile TOP=../.. \
    T_A=linux-x86_64 install
make[2]: Entering directory `/scratch/jenkins/workspace/exampleCPP_PullRequests/BASE/3.14.12.5/USE_MB/MB_NO/test/O.linux-x86_64'

/usr/bin/g++ -c  -D_GNU_SOURCE -D_DEFAULT_SOURCE            -D_X86_64_  -DUNIX  -Dlinux     -O3 -g   -Wall       -m64      -MMD -I. -I../O.Common -I. -I.. -I../../include/pv/os/Linux -I../../include/pv      -I ../../include    ../pvaClientTest.cpp 
../pvaClientTest.cpp:14:26: fatal error: pv/pvaClient.h: No such file or directory
compilation terminated.

Does anyone have a idea why?
Is it a problem  with jenkins?

I also have a problem with static builds but will describe this in a separate message.

**Comment by mrkraimer** [comment]
On 01/26/2016 11:50 AM, Andrew Johnson wrote:
>
> @mrkraimer Marty, I haven't looked at this pull request yet but the VxWorks and RTEMS problems are usually library link order issues (shared libraries can be linked in any order, but for non-shared libraries the order in which libraries are linked matters; libca and libCom must appear last). You can probably find most of those issues yourself by doing a completely static build: In your base/configure/CONFIG_SITE file, set STATIC_BUILD=YES and SHARED_LIBRARIES=NO and do a make distclean all in all modules, in dependency order starting from Base.
>
> —
> Reply to this email directly or view it on GitHub.

I did a pull, clean, and build with the following RELEASE.local

/home/epicsv4/master
mrk> cat RELEASE.local
EPICS4_DIR=/home/epicsv4/master
EXAMPLE=${EPICS4_DIR}/exampleCPP
PVDATABASE=${EPICS4_DIR}/pvDatabaseCPP
PVACLIENT=${EPICS4_DIR}/pvaClientCPP
PVASRV=${EPICS4_DIR}/pvaSrv
PVACCESS=${EPICS4_DIR}/pvAccessCPP
NORMATIVETYPES=${EPICS4_DIR}/normativeTypesCPP
PVDATA=${EPICS4_DIR}/pvDataCPP
PVCOMMON=${EPICS4_DIR}/pvCommonCPP

EPICS_BASE=/home/install/epics/base-3.14.12.5STATICBUILD
#EPICS_BASE=/home/install/epics/base-3.14.12.5
#EPICS_BASE=/home/install/epics/base-3.15.3



What I get for stderr while building is

_________________start___________
_________________ + /home/epicsv4/master/pvCommonCPP + ___________
_________________ + /home/epicsv4/master/pvDataCPP + ___________
...
_________________ + /home/epicsv4/master/exampleCPP + ___________
/home/epicsv4/master/normativeTypesCPP/lib/linux-x86_64/libnt.a(ntscalar.o): In function `epics::nt::NTScalar::attachAlarm(epics::pvData::PVAlarm&) const':
/home/epicsv4/master/normativeTypesCPP/src/O.linux-x86_64/../../src/nt/ntscalar.cpp:217: undefined reference to `epics::pvData::PVAlarm::attach(std::tr1::shared_ptr<epics::pvData::PVField> const&)'
/home/epicsv4/master/normativeTypesCPP/lib/linux-x86_64/libnt.a(ntscalar.o): In function `epics::nt::NTScalar::attachControl(epics::pvData::PVControl&) const':
/home/epicsv4/master/normativeTypesCPP/src/O.linux-x86_64/../../src/nt/ntscalar.cpp:235: undefined reference to `epics::pvData::PVControl::attach(std::tr1::shared_ptr<epics::pvData::PVField> const&)'
/home/epicsv4/master/normativeTypesCPP/lib/linux-x86_64/libnt.a(ntscalar.o): In function `epics::nt::NTScalar::attachDisplay(epics::pvData::PVDisplay&) const':
/home/epicsv4/master/normativeTypesCPP/src/O.linux-x86_64/../../src/nt/ntscalar.cpp:226: undefined reference to `epics::pvData::PVDisplay::attach(std::tr1::shared_ptr<epics::pvData::PVField> const&)'
/home/epicsv4/master/normativeTypesCPP/lib/linux-x86_64/libnt.a(ntscalarArray.o): In function `epics::nt::NTScalarArray::attachDisplay(epics::pvData::PVDisplay&) const':
/home/epicsv4/master/normativeTypesCPP/src/O.linux-x86_64/../../src/nt/ntscalarArray.cpp:234: undefined reference to `epics::pvData::PVDisplay::attach(std::tr1::shared_ptr<epics::pvData::PVField> const&)'
/home/epicsv4/master/normativeTypesCPP/lib/linux-x86_64/libnt.a(ntscalarArray.o): In function `epics::nt::NTScalarArray::attachAlarm(epics::pvData::PVAlarm&) const':
/home/epicsv4/master/normativeTypesCPP/src/O.linux-x86_64/../../src/nt/ntscalarArray.cpp:225: undefined reference to `epics::pvData::PVAlarm::attach(std::tr1::shared_ptr<epics::pvData::PVField> const&)'
/home/epicsv4/master/normativeTypesCPP/lib/linux-x86_64/libnt.a(ntscalarArray.o): In function `epics::nt::NTScalarArray::attachControl(epics::pvData::PVControl&) const':
/home/epicsv4/master/normativeTypesCPP/src/O.linux-x86_64/../../src/nt/ntscalarArray.cpp:243: undefined reference to `epics::pvData::PVControl::attach(std::tr1::shared_ptr<epics::pvData::PVField> const&)'
/home/epicsv4/master/normativeTypesCPP/lib/linux-x86_64/libnt.a(ntenum.o): In function `epics::nt::NTEnum::attachAlarm(epics::pvData::PVAlarm&) const':
/home/epicsv4/master/normativeTypesCPP/src/O.linux-x86_64/../../src/nt/ntenum.cpp:178: undefined reference to `epics::pvData::PVAlarm::attach(std::tr1::shared_ptr<epics::pvData::PVField> const&)'
collect2: error: ld returned 1 exit status
make[3]: *** [exampleDatabaseMain] Error 1


I also tried just building arrayPerformance

mrk> pwd
/home/epicsv4/master/exampleCPP/arrayPerformance
mrk> make

It does compile all the array performance code.
BUT it can not locate any of the statically built libraries from the other modules: pvDataCPP, etc.

For example I get:

home/epicsv4/master/exampleCPP/arrayPerformance/src/O.linux-x86_64/../../src/code/arrayPerformance.cpp:34: undefined reference to `epics::pvData::getStandardPVField()'

**Comment by ralphlange** [comment]
As I have written in an earlier comment:

The compiler command line misses the `-I/tmp/stuff/include/os/Linux -I/tmp/stuff/include` settings that all compiler lines before have.

These settings are blown up from the environment variable EPICS_BASE that should be set to `/tmp/stuff`.

As the previous lines are working, the most probable explanation is that EPICS_BASE is being overwritten somewhere for the `test` directory.

**Comment by mrkraimer** [comment]
On 02/01/2016 11:13 AM, Ralph Lange wrote:
>
> As I have written in an earlier comment:
>
> The compiler command line misses the |-I/tmp/stuff/include/os/Linux 
> -I/tmp/stuff/include| settings that all compiler lines before have.
>
> These settings are blown up from the environment variable EPICS_BASE 
> that should be set to |/tmp/stuff|.
>
> As the previous lines are working, the most probable explanation is 
> that EPICS_BASE is being overwritten somewhere for the |test| directory.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/4#issuecomment-178048216>.
>


Note:

mrk> pwd
/home/epicsv4/master/exampleCPP
mrk> grep -R EPICS_BASE configure test
configure/ExampleRELEASE.local:TEMPLATE_TOP=$(EPICS_BASE)/templates/makeBaseApp/top
configure/ExampleRELEASE.local:EPICS_BASE=/home/install/epics/base
configure/RELEASE:# "gnumake rebuild" in the top level directory after 
EPICS_BASE
configure/CONFIG:RULES = $(EPICS_BASE)
mrk>


Thus as far as I can see EPICS_BASE is NOT being overwritten somewhere 
for the |test| directory.

I am building pvCommonCPP, ..., exampleCPP in
/home/epicsv4/master

This directory has a RELEASE.local that has the definitions:

> EPICS4_DIR=/home/epicsv4/master
> EXAMPLE=${EPICS4_DIR}/exampleCPP
> PVDATABASE=${EPICS4_DIR}/pvDatabaseCPP
> PVACLIENT=${EPICS4_DIR}/pvaClientCPP
> PVASRV=${EPICS4_DIR}/pvaSrv
> PVACCESS=${EPICS4_DIR}/pvAccessCPP
> NORMATIVETYPES=${EPICS4_DIR}/normativeTypesCPP
> PVDATA=${EPICS4_DIR}/pvDataCPP
> PVCOMMON=${EPICS4_DIR}/pvCommonCPP
>
> #EPICS_BASE=/home/install/epics/base-3.14.12.5STATICBUILD
> EPICS_BASE=/home/install/epics/base-3.14.12.5
> #EPICS_BASE=/home/install/epics/base-3.15.3


And again all of the above build OK except for exampleCPP/test

**Comment by mrkraimer** [comment]
The last message said
And again all of the above build OK except for exampleCPP/test

It should have said:

When I build in my area every thing build just fine.
Jenkins builds OK except for exampleCPP/test

**Comment by ralphlange** [comment]
If test doesn't override EPICS_BASE, it doesn't set it. (Else it would be set.)
Double-check that the test structure (i.e. the outer configure) reads the RELEASE.local that the Jenkins build script generates.
Restriction: Jenkins jobs must not create files outside of their workspace. This may be the main difference to your local build.

**Comment by anjohnson** [comment]
`exampleCPP/test` is not an embedded top, that's one way in which it's different to all the other sub-directories.

The others all contain their own configure directory with a `configure/RELEASE` file that does
``` Makefile
-include $(TOP)/../../RELEASE.local
-include $(TOP)/../RELEASE.local
-include $(TOP)/configure/RELEASE.local
```
The `exampleCPP/jenkins/cloudbees_build` script generates a `RELEASE.local` file in `${WORKSPACE}` i.e. in the exampleCPP top-level directory. For the above `configure/RELEASE` files then the important line when building on cloudbees is the second one (for Marty's build it's probably the first one, and for the APS Jenkins build it will be the third one). However the top-level `configure/RELEASE` file as used when building the test sub-directory does this:
``` Makefile
-include $(TOP)/../RELEASE.local
-include $(TOP)/configure/RELEASE.local
```
Thus when building on cloudbees the top-level build doesn't include the generated `RELEASE.local` file; you need to add this line to the `exampleCPP/configure/RELEASE` file:
``` Makefile
-include $(TOP)/RELEASE.local
```

If you're wondering how the rest of the build in the test directory manages to work, it's because the `cloudbees_build` script also sets the EPICS_BASE environment variable which gnumake uses to find the other parts. The list of include directories however has to be generated from a real `RELEASE` file.

Please try making that change and let's see whether it fixes everything.

**Comment by anjohnson** [comment]
I lied, there is no APS Jenkins build of exampleCPP yet, and if there was it would also fail because it would need the embedded `configure/RELEASE` files to do
``` Makefile
-include $(TOP)/../configure/RELEASE.local
```
My builds all create their RELEASE.local file in `${WORKSPACE}/configure`. Hmm, so do the `jenkins/cloudbees_build` scripts in all of the *other* V4 modules; maybe you should fix that and adjust the embedded `configure/RELEASE` files by adding the line above to all of them.

**Comment by ralphlange** [comment]
Correct. The cloudbees_build job should create the RELEASE.local in `TOP/configure`. TOP was never an agreed-upon location for it.

**Comment by mrkraimer** [comment]
On 02/03/2016 11:54 AM, Andrew Johnson wrote:
>
> |exampleCPP/test| is not an embedded top, that's one way in which it's 
> different to all the other sub-directories.
>
> The others all contain their own configure directory with a 
> |configure/RELEASE| file that does
>
> -include  $(TOP)/../../RELEASE.local
> -include  $(TOP)/../RELEASE.local
> -include  $(TOP)/configure/RELEASE.local
>
> The |exampleCPP/jenkins/cloudbees_build| script generates a 
> |RELEASE.local| file in |${WORKSPACE}| i.e. in the exampleCPP 
> top-level directory. For the above |configure/RELEASE| files then the 
> important line when building on cloudbees is the second one (for 
> Marty's build it's probably the first one, and for the APS Jenkins 
> build it will be the third one). However the top-level 
> |configure/RELEASE| file as used when building the test sub-directory 
> does this:
>
> -include  $(TOP)/../RELEASE.local
> -include  $(TOP)/configure/RELEASE.local
>
> Thus when building on cloudbees the top-level build doesn't include 
> the generated |RELEASE.local| file; you need to add this line to the 
> |exampleCPP/configure/RELEASE| file:
>
> -include  $(TOP)/RELEASE.local
>
> If you're wondering how the rest of the build in the test directory 
> manages to work, it's because the |cloudbees_build| script also sets 
> the EPICS_BASE environment variable which gnumake uses to find the 
> other parts. The list of include directories however has to be 
> generated from a real |RELEASE| file.
>
> Please try making that change and let's see whether it fixes everything.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/4#issuecomment-179343047>.
>


I made the change that Andrew suggested.

Now the test does run successfully but then console output ends with:

**** Unable to start "CA Repeater" process.
pvaClientTest.t ............... ok
pvaClientTestPutData.t ........ ok
pvaClientTestGetData.t ........ ok
pvaClientTestMonitorData.t .... ok
pvaClientTestPutGetMonitor.t .. ok
pvaClientTestPutGet.t ......... ok
All tests successful.
Files=6, Tests=119, 17 wallclock secs ( 0.03 usr  0.04 sys +  0.28 cusr  0.26 csys =  0.61 CPU)
Result: PASS
make[2]: Leaving directory `/scratch/jenkins/workspace/exampleCPP_PullRequests/BASE/3.14.12.5/USE_MB/MB_NO/test/O.linux-x86_64'
make[1]: Leaving directory `/scratch/jenkins/workspace/exampleCPP_PullRequests/BASE/3.14.12.5/USE_MB/MB_NO/test'
++ tar -czf pvDatabase.CB-dist.tar.gz lib include dbd COPYRIGHT LICENSE
tar: lib: Cannot stat: No such file or directory
tar: include: Cannot stat: No such file or directory
tar: dbd: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Build step 'Execute shell' marked build as failure
An attempt to send an e-mail to empty list of recipients, ignored.
Finished: FAILURE

**Comment by mrkraimer** [comment]
On 02/03/2016 12:26 PM, Andrew Johnson wrote:
>
> I lied, there is no APS Jenkins build of exampleCPP yet, and if there 
> was it would also fail because it would need the embedded 
> |configure/RELEASE| files to do
>
> -include  $(TOP)/../configure/RELEASE.local
>
> My builds all create their RELEASE.local file in 
> |${WORKSPACE}/configure|. Hmm, so do the |jenkins/cloudbees_build| 
> scripts in all of the /other/ V4 modules; maybe you should fix that 
> and adjust the embedded |configure/RELEASE| files by adding the line 
> above to all of them.
>

I did but still get:

pvaClientTest.t ............... ok
pvaClientTestPutData.t ........ ok
pvaClientTestGetData.t ........ ok
pvaClientTestMonitorData.t .... ok
pvaClientTestPutGetMonitor.t .. ok
pvaClientTestPutGet.t ......... ok
All tests successful.
Files=6, Tests=119, 17 wallclock secs ( 0.04 usr  0.03 sys +  0.27 cusr  0.30 csys =  0.64 CPU)
Result: PASS
make[2]: Leaving directory `/scratch/jenkins/workspace/exampleCPP_PullRequests/BASE/3.14.12.5/USE_MB/MB_NO/test/O.linux-x86_64'
make[1]: Leaving directory `/scratch/jenkins/workspace/exampleCPP_PullRequests/BASE/3.14.12.5/USE_MB/MB_NO/test'
++ tar -czf pvDatabase.CB-dist.tar.gz lib include dbd COPYRIGHT LICENSE
tar: lib: Cannot stat: No such file or directory
tar: include: Cannot stat: No such file or directory
tar: dbd: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Build step 'Execute shell' marked build as failure
An attempt to send an e-mail to empty list of recipients, ignored.
Finished: FAILURE

**Comment by anjohnson** [comment]
```
tar -czf pvDatabase.CB-dist.tar.gz lib include dbd COPYRIGHT LICENSE
tar: lib: Cannot stat: No such file or directory
tar: include: Cannot stat: No such file or directory
tar: dbd: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```
The last line of the `jenkins/cloudbees_build` script is wrong. This module doesn't provide any libraries or header files for downstream modules to use, so it doesn't make much sense to generate a tarfile containing the results of building it. You could tar up the products of the individual examples, but I don't think there's very much point in doing that for this module. It would be simplest to just delete that line from the script, which should allow the merge checks to complete (the filename that tar is being asked to generate is also wrong, it should have been `example.CB-dist.tar.gz`).

While you're working in the `jenkins` directory, please also delete the `cloudbees_hgweb` script which is no longer used/needed.

**Comment by mrkraimer** [comment]
On 02/04/2016 11:18 AM, Andrew Johnson wrote:
> |tar -czf pvDatabase.CB-dist.tar.gz lib include dbd COPYRIGHT LICENSE 
> tar: lib: Cannot stat: No such file or directory tar: include: Cannot 
> stat: No such file or directory tar: dbd: Cannot stat: No such file or 
> directory tar: Exiting with failure status due to previous errors |
>
> The last line of the |jenkins/cloudbees_build| script is wrong. This 
> module doesn't provide any libraries or header files for downstream 
> modules to use, so it doesn't make much sense to generate a tarfile 
> containing the results of building it. You could tar up the products 
> of the individual examples, but I don't think there's very much point 
> in doing that for this module. It would be simplest to just delete 
> that line from the script, which should allow the merge checks to 
> complete (the filename that tar is being asked to generate is also 
> wrong, it should have been |example.CB-dist.tar.gz|).
>
> While you're working in the |jenkins| directory, please also delete 
> the |cloudbees_hgweb| script which is no longer used/needed.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/exampleCPP/pull/4#issuecomment-179926145>.
>

OK I did that.

**Comment by mrkraimer** [comment]
The last change did make all checks pass.
However there is a problem in that
make runtests
only works with base 3.14 but not with 3.15

with
https://openepics.ci.cloudbees.com/view/EPICS%20V4%20C++/job/exampleCPP_PullRequests/BASE=3.14.12.5,USE_MB=MB_NO/

The console output ends with

pvaClientTest.t ............... ok
pvaClientTestPutData.t ........ ok
pvaClientTestGetData.t ........ ok
pvaClientTestMonitorData.t .... ok
pvaClientTestPutGetMonitor.t .. ok
pvaClientTestPutGet.t ......... ok
All tests successful.
Files=6, Tests=119, 17 wallclock secs ( 0.04 usr  0.03 sys +  0.22 cusr  0.26 csys =  0.55 CPU)
Result: PASS
make[2]: Leaving directory `/scratch/jenkins/workspace/exampleCPP_PullRequests/BASE/3.14.12.5/USE_MB/MB_NO/test/O.linux-x86_64'
make[1]: Leaving directory `/scratch/jenkins/workspace/exampleCPP_PullRequests/BASE/3.14.12.5/USE_MB/MB_NO/test'
Finished: SUCCESS

But
https://openepics.ci.cloudbees.com/view/EPICS%20V4%20C++/job/exampleCPP_PullRequests/BASE=3.15.2,USE_MB=MB_NO/

ends with
pvaClientTest.t ............... ok
pvaClientTestPutData.t ........ ok
pvaClientTestGetData.t ........ ok
pvaClientTestMonitorData.t .... ok
Bailout called.  Further testing stopped:  channel connection exception 'channel PVRdouble PvaClientChannel::connect PVRdouble createChannel failed'
FAILED--Further testing stopped: channel connection exception 'channel PVRdouble PvaClientChannel::connect PVRdouble createChannel failed'
make[2]: [runtests] Error 134 (ignored)
make[2]: Leaving directory `/scratch/jenkins/workspace/exampleCPP_PullRequests/BASE/3.15.2/USE_MB/MB_NO/test/O.linux-x86_64'
make[1]: Leaving directory `/scratch/jenkins/workspace/exampleCPP_PullRequests/BASE/3.15.2/USE_MB/MB_NO/test'
Finished: SUCCESS

This is related to a problem discussed in
https://github.com/epics-base/pvaSrv/issues/22

I am going to add one more comment to that issue and then close it.

I think that the problem is in pvAccessCPP so I will open a new issue in it.

I am also going to merge this pull request.

**Pull request merged**
