### PR TITLE
pva2pva replaces pvaSrv

### PR DESCRIPTION
**Pull request by mrkraimer**

### CODE REVIEW

**Comment by anjohnson** [comment]
The Travis-CI and Cloudbees Jenkins builds are failing for this pull request because there is no job for building pva2pva on either of them yet (APS Jenkins is similarly lacking), and the CI scripts in this module will need modifying to switch away from pvaSrv as well.

Interestingly the WINE static build on Travis passed, which seems rather strange...

Marty, please don't merge this until the CI changes have been done and the PR checks are passing.

**Comment by ralphlange** [comment]
The Travis-CI scripts are in place. I wouldn't have asked Marty to move on without them.
The single module build (epics-base/pva2pva repository) was not enabled yet on Travis (I just did that), but it was certainly build as part of the exampleCPP and the bundle builds.

As the plan is to move away fro CloudBees, I currently do not plan to add CloudBees jobs for this repository.

**Comment by ralphlange** [comment]
build-deps.sh has been removed on the master branch. All CI scripts in all modules are in the .ci directory.

**Comment by mrkraimer** [comment]
The continuous-integration/travis-ci/pr  builds look like they fail on
make runtests

I do not understand default failure. Is this still CloudBees?
If so should this still be built?

**Comment by ralphlange** [comment]
"default" is CloudBees. (You can see it following the "Details" link.)
Please ignore for the moment - don't know if the CloudBees jobs will be kept.

**Comment by mrkraimer** [comment]
I am looking at the travis build for 14.1 and also for 14.2
For both everything looks OK until it is running the test, i. e. the equivalent of 
make runtests.

I see 

make -C ./test tapfiles 
make[1]: Entering directory `/home/travis/build/epics-base/exampleCPP/test'
make -C O.linux-x86_64 -f ../Makefile TOP=../.. \
	    T_A=linux-x86_64 tapfiles
make[2]: Entering directory `/home/travis/build/epics-base/exampleCPP/test/O.linux-x86_64'
perl -CSD pvaClientTest.t -tap > pvaClientTest.tap
Use of uninitialized value $arch in concatenation (.) or string at ../exampleDb.pm line 15.
open3: exec of /home/travis/build/epics-base/exampleCPP/database/bin//exampleDatabase st.cmd failed at ../IOC.pm line 85.
make[2]: [pvaClientTest.tap] Error 2 (ignored)
perl -CSD pvaClientTestPutData.t -tap > pvaClientTestPutData.tap
Use of uninitialized value $arch in concatenation (.) or string at ../exampleDb.pm line 15.
open3: exec of /home/travis/build/epics-base/exampleCPP/database/bin//exampleDatabase st.cmd failed at ../IOC.pm line 85.
make[2]: [pvaClientTestPutData.tap] Error 2 (ignored)
perl -CSD pvaClientTestGetData.t -tap > pvaClientTestGetData.tap
Use of uninitialized value $arch in concatenation (.) or string at ../exampleDb.pm line 15.
open3: exec of /home/travis/build/epics-base/exampleCPP/database/bin//exampleDatabase st.cmd failed at ../IOC.pm line 85.
make[2]: [pvaClientTestGetData.tap] Error 2 (ignored)
perl -CSD pvaClientTestMonitorData.t -tap > pvaClientTestMonitorData.tap
Use of uninitialized value $arch in concatenation (.) or string at ../exampleDb.pm line 15.
open3: exec of /home/travis/build/epics-base/exampleCPP/database/bin//exampleDatabase st.cmd failed at ../IOC.pm line 85.
make[2]: [pvaClientTestMonitorData.tap] Error 2 (ignored)
perl -CSD pvaClientTestPutGetMonitor.t -tap > pvaClientTestPutGetMonitor.tap
Use of uninitialized value $arch in concatenation (.) or string at ../exampleDb.pm line 15.
open3: exec of /home/travis/build/epics-base/exampleCPP/database/bin//exampleDatabase st.cmd failed at ../IOC.pm line 85.
make[2]: [pvaClientTestPutGetMonitor.tap] Error 2 (ignored)
perl -CSD pvaClientTestPutGet.t -tap > pvaClientTestPutGet.tap
Use of uninitialized value $arch in concatenation (.) or string at ../exampleDb.pm line 15.
open3: exec of /home/travis/build/epics-base/exampleCPP/database/bin//exampleDatabase st.cmd failed at ../IOC.pm line 85.
make[2]: [pvaClientTestPutGet.tap] Error 2 (ignored)
make[2]: Leaving directory `/home/travis/build/epics-base/exampleCPP/test/O.linux-x86_64'
make[1]: Leaving directory `/home/travis/build/epics-base/exampleCPP/test'
+find . -name *.tap -print0
+xargs -0 -n1 prove -e cat -f
./test/O.linux-x86_64/pvaClientTest.tap .. 
                                             
./test/O.linux-x86_64/pvaClientTest.tap .. [31mNo subtests run [0m

Ralph,

Do You know what is wrong?

**Comment by ralphlange** [comment]
The messages are quite clear, I think:

> Use of uninitialized value $arch in concatenation (.) ...

$arch is not being set.

> open3: exec of /home/travis/build/epics-base/exampleCPP/database/bin//exampleDatabase ...

See the double slash characters? That's where the $arch (target architecture) should be. The resulting path does not exist, and the IOC cannot be started.

**Comment by ralphlange** [comment]
exampleDb.pm reads the architecture from the environment, so obviously EPICS_HOST_ARCH is not being set when running the tests.

**Comment by mrkraimer** [comment]
Looking at the .ci/travis-prepare.sh in pvDataCPP I am making the following change in exampleCPP

mrk> git diff .ci/travis-prepare.sh
diff --git a/.ci/travis-prepare.sh b/.ci/travis-prepare.sh
index fd146a2..5610611 100755
--- a/.ci/travis-prepare.sh
+++ b/.ci/travis-prepare.sh
@@ -32,6 +32,8 @@ then
   fi
 fi
 
+cd "$CURDIR"
+
 cat << EOF > $CURDIR/configure/RELEASE.local
 EPICS_BASE=$HOME/.source/epics-base
 EOF
mrk> 
Lets see what happens.

**Comment by ralphlange** [comment]
I spent two days to make the scripts all the same across all 11 modules.
Please don't start changing them.

**Comment by ralphlange** [comment]
Careful. Please pull from GitHub first: I have removed you last two commits, as they were not changing anything.
The tests now fail because pvAccess is not connecting.

**Comment by mrkraimer** [comment]
Should we (You?) close this pull request?
Then when you are ready I can issue a new pull request.

**Comment by ralphlange** [comment]
Why close it?

**Comment by ralphlange** [comment]
I think the example module should be fixed, shouldn't it?

**Comment by mrkraimer** [comment]
The failure is because of a change to pvAccessCPP that makes pvDatabaseCPP fail
I have fixed pvDatabaseCPP but am not quite ready to commit.
But should be ready by the end of today.

**Comment by ralphlange** [comment]
I don't think so.
> ./test/O.linux-x86_64/pvaClientTest.tap .. 1/7 Bailout called.  Further testing stopped:  channel example exception 'channel DBRdouble01 PvaClientChannel::connect  not connected'

doesn't look like being related to pvDatabase, and locally on my Linux VM the tests pass.

I rather think it is being related to Travis-CI builds running in a Docker container, which might have different network behavior.
As next step I will try running the build on a local Travis container in my VM.

**Pull request merged**
